import { LocationCategory, PetFriendlyPlace } from '../types/location';

export const samplePetFriendlyPlaces: PetFriendlyPlace[] = [
    {
        id: '1',
        name: 'Paws & Plates',
        address: '123 Pet Street, Shanghai',
        latitude: 31.2304,
        longitude: 121.4737,
        adInfo: null,
        addressComponent: null,
        isPetFriendly: true,
        petSize: 'medium',
        petType: 'dog',
        zone: 'Xuhui District',
        description: 'A cozy restaurant with outdoor seating for pets and special pet menus',
        category: LocationCategory.RESTAURANT,
        rating: 4.5,
        reviews: 128,
        amenities: ['Outdoor seating', 'Pet water bowls', 'Pet treats'],
        photos: ['https://example.com/paws-plates-1.jpg'],
        createdAt: '2024-01-15',
        updatedAt: '2024-03-10',
    },
    {
        id: '2',
        name: 'Happy Tails Dog Park',
        address: '456 Green Avenue, Shanghai',
        latitude: 31.2356,
        longitude: 121.4789,
        adInfo: null,
        addressComponent: null,
        isPetFriendly: true,
        petSize: 'all',
        petType: 'dog',
        zone: "Jing'an District",
        description: 'Large fenced dog park with separate areas for small and large dogs',
        category: LocationCategory.PARK,
        rating: 4.8,
        reviews: 215,
        amenities: ['Agility equipment', 'Water stations', 'Waste bags'],
        photos: ['https://example.com/dog-park-1.jpg'],
        createdAt: '2023-11-20',
        updatedAt: '2024-02-28',
    },
    {
        id: '3',
        name: 'Pet Paradise Store',
        address: '789 Animal Road, Shanghai',
        latitude: 31.2333,
        longitude: 121.4755,
        adInfo: null,
        addressComponent: null,
        isPetFriendly: true,
        petSize: 'all',
        petType: 'all',
        zone: 'Huangpu District',
        description: 'Comprehensive pet store with food, toys, and grooming services',
        category: LocationCategory.PET_STORE,
        rating: 4.6,
        reviews: 178,
        amenities: ['Grooming', 'Self-wash station', 'Vet clinic'],
        photos: ['https://example.com/pet-store-1.jpg'],
        createdAt: '2024-02-05',
        updatedAt: '2024-03-15',
    },
    {
        id: '4',
        name: 'The Woofington Hotel',
        address: '101 Bark Boulevard, Shanghai',
        latitude: 31.2378,
        longitude: 121.4812,
        adInfo: null,
        addressComponent: null,
        isPetFriendly: true,
        petSize: 'small,medium',
        petType: 'dog,cat',
        zone: 'Pudong District',
        description: 'Luxury hotel with pet-friendly rooms and dedicated pet concierge',
        category: LocationCategory.HOTEL,
        rating: 4.7,
        reviews: 192,
        amenities: ['Pet beds', 'Room service for pets', 'Dog walking service'],
        photos: ['https://example.com/hotel-1.jpg'],
        createdAt: '2023-12-10',
        updatedAt: '2024-03-05',
        distance: 1.2,
    },
];

export const samplePicture =
    'https://blog-1321748307.cos.ap-shanghai.myqcloud.com/img/IMG_0472.jpeg';
