import { PlaceCategory, PetFriendlyPlace, Review } from '../types/place';

export const samplePetFriendlyPlaces: PetFriendlyPlace[] = [
    {
        id: '1',
        name: 'Paws & Plates',
        address: '123 Pet Street, Shanghai',
        latitude: 31.2304,
        longitude: 121.4737,
        adInfo: null,
        addressComponent: null,
        isPetFriendly: true,
        petSize: 'medium',
        petType: 'dog',
        zone: 'Xuhui District',
        description: 'A cozy restaurant with outdoor seating for pets and special pet menus',
        category: PlaceCategory.RESTAURANT,
        rating: 4.5,
        reviews: 128,
        facilities: {
            wifi: true,
            parking: true,
            petSnacks: true,
            PetToys: true,
            PetToilet: true,
        },
        photos: ['https://example.com/paws-plates-1.jpg'],
        createdAt: '2024-01-15',
        updatedAt: '2024-03-10',
    },
    {
        id: '2',
        name: 'Happy Tails Dog Park',
        address: '456 Green Avenue, Shanghai',
        latitude: 31.2356,
        longitude: 121.4789,
        adInfo: null,
        addressComponent: null,
        isPetFriendly: true,
        petSize: 'all',
        petType: 'dog',
        zone: "Jing'an District",
        description: 'Large fenced dog park with separate areas for small and large dogs',
        category: PlaceCategory.PARK,
        rating: 4.8,
        reviews: 215,
        facilities: {
            wifi: true,
            parking: true,
            petSnacks: false,
            PetToys: true,
            PetToilet: true,
        },
        photos: ['https://example.com/dog-park-1.jpg'],
        createdAt: '2023-11-20',
        updatedAt: '2024-02-28',
    },
    {
        id: '3',
        name: 'Pet Paradise Store',
        address: '789 Animal Road, Shanghai',
        latitude: 31.2333,
        longitude: 121.4755,
        adInfo: null,
        addressComponent: null,
        isPetFriendly: true,
        petSize: 'all',
        petType: 'all',
        zone: 'Huangpu District',
        description: 'Comprehensive pet store with food, toys, and grooming services',
        category: PlaceCategory.PET_STORE,
        rating: 4.6,
        reviews: 178,
        facilities: {
            wifi: true,
            parking: true,
            petSnacks: true,
            PetToys: true,
            PetToilet: false,
        },
        photos: ['https://example.com/pet-store-1.jpg'],
        createdAt: '2024-02-05',
        updatedAt: '2024-03-15',
    },
    {
        id: '4',
        name: 'The Woofington Hotel',
        address: '101 Bark Boulevard, Shanghai',
        latitude: 31.2378,
        longitude: 121.4812,
        adInfo: null,
        addressComponent: null,
        isPetFriendly: true,
        petSize: 'small,medium',
        petType: 'dog,cat',
        zone: 'Pudong District',
        description: 'Luxury hotel with pet-friendly rooms and dedicated pet concierge',
        category: PlaceCategory.HOTEL,
        rating: 4.7,
        reviews: 192,
        facilities: {
            wifi: true,
            parking: true,
            petSnacks: true,
            PetToys: true,
            PetToilet: true,
        },
        photos: ['https://example.com/hotel-1.jpg'],
        createdAt: '2023-12-10',
        updatedAt: '2024-03-05',
        distance: 1.2,
    },
];

export const samplePicture =
    'https://blog-1321748307.cos.ap-shanghai.myqcloud.com/img/IMG_0472.jpeg';

export const sampleUserReviews: Review[] = [
    {
        title: 'Great place for pets',
        content:
            'I love taking my dog to Paws & Plates! The outdoor seating is perfect for pets, and the staff are always friendly.',
        username: 'doglover123',
        userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
        date: new Date('2023-12-15'),
        rating: 5,
    },
    {
        title: 'Fun for all dogs',
        content:
            'Happy Tails Dog Park is a great place for dogs to run and play. My dog loves the agility equipment!',
        username: 'puppyfan',
        userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
        date: new Date('2024-12-15'),
        rating: 4,
    },
];
